### Variable 
@url = localhost:8084



#######################################################
### Organize ##########################################
#######################################################

### 조직 생성
POST {{url}}/api/organizes

{
  "name": "demo-org",
  "path": "demo",
  "ownerId": 1,
  "description": "demo organize"
}

### 조직 목록 조회
GET {{url}}/api/organizes

### 조직 상세 조회
GET {{url}}/api/organizes/1

### 조직 수정
PUT {{url}}/api/organizes/1

{
  "name": "demo-org",
  "description": "updated"
}

### 조직 삭제
DELETE {{url}}/api/organizes/4

#######################################################
### Repository ########################################
#######################################################

### 저장소 등록
POST {{url}}/api/repositories

{
    "repoName": "bbb",
    "mainBranch": "main",
    "readme": true,
    "username": "heykia3",
    "email": "heykia3@protonmail.com",
    "message": "Initial Commit",
    "organizeId": 5,
    "path": "bbb",
    "visibility": "PUBLIC",
    "repositoryType": "GIT"
}

### 저장소목록 조회
### GET {{url}}/api/repositories

### 저장소 상세 조회
GET {{url}}/api/repositories/3

### 저장소 삭제
DELETE {{url}}/api/repositories/4


#######################################################
### Runner ############################################
#######################################################

### Runner 등록
POST {{url}}/runners

{
  "scopeType": "GLOBAL",
  "description": "hihi"
}

### Repository 목록 조회
GET {{url}}/runners

### Repository 상세 조회
GET {{url}}/runners/4

### Repository 단건 삭제
DELETE {{url}}/runners/


### Runner 활성화
POST {{url}}/runners/6/activate
Accept: application/json
Content-Type: application/json

{
  "token": "RNR-85B46DCBB9BF4A4F896B3E3E"
}
