grpc:
  server:
    port: 9090
---

# 기본 설정
server:
  port: 8084
  servlet:
    context-path: /
---
# Mybatis 설정
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
---
# Swagger 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    operations-sorter: method
    display-request-duration: true
    persist-authorization: true

---
jgitkins:
  server:
    runtime:
      rest-host: localhost
      rest-port: ${server.port:8084}
      rest-base-path: /api
      grpc-host: localhost
      grpc-port: ${grpc.server.port:9090}
      poll-interval-ms: 5000
      busy-wait-interval-ms: 1000
      volumn: ${user.home}
